#!/usr/bin/env bash

function prompt() {
  local SOURCE="$( command cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  local GIT_PROMPT_SH="${SOURCE}/gitprompt.sh"

  if [ -f "${GIT_PROMPT_SH}" ]; then
    GIT_PROMPT_ONLY_IN_REPO=0
    # GIT_PROMPT_FETCH_REMOTE_STATUS=0
    GIT_PROMPT_IGNORE_SUBMODULES=1
    # GIT_PROMPT_WITH_VIRTUAL_ENV=0
    # GIT_PROMPT_SHOW_UPSTREAM=1
    # GIT_PROMPT_SHOW_UNTRACKED_FILES=normal
    # GIT_PROMPT_SHOW_CHANGED_FILES_COUNT=0

    GIT_PROMPT_THEME=BlackOrWhite
    GIT_PROMPT_BLACK_OR_WHITE_THEME_PS1_COLOR=white
    GIT_PROMPT_BLACK_OR_WHITE_THEME_SHOW_TIME_INSTEAD_OF_USER=1
    #GIT_PROMPT_BLACK_OR_WHITE_THEME_SHOW_LAST_COMMAND_STATE=1
    GIT_PROMPT_BLACK_OR_WHITE_THEME_SHOW_POWERLINE_ICON=1
    #GIT_PROMPT_BLACK_OR_WHITE_THEME_SHOW_NERD_FONTS_ICONS=1
    source "${GIT_PROMPT_SH}"
  fi
}

prompt

